src/Chirp.Web/Pages/AboutMePage.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Graph;
using Azure.Identity;

namespace Chirp.Web.Pages;

public class AboutMePageModel : PageModel
{
    // Holds the functionality for the About Me page.

    // The cheep repository for fetching the user's cheeps.
    public ICheepRepository _cheepRepository;

    // The author repository for fetching the user's followers and the authors that the user follows.
    public IAuthorRepository _authorRepository;
    private readonly IConfiguration _config;

    // The list of cheeps written by the user, to be displayed on the About Me page.
    public List<CheepDto>? Cheeps { get; set; }

    // The IDs of the followed and following authors, used to fetch the names of those authors.
    public List<Guid>? FollowedID { get; set; }
    public List<Guid>? FollowersID { get; set; }

    // The names of the followwing and followed authors, to be displayed.
    public List<string>? FollowersName { get; set; }
    public List<string>? FollowedName { get; set; }

    // The name of the user
    public string? Author { get; set; }

    // The email of the user
    public string? Email { get; set; }
    public string? OID { get; set; }




    public AboutMePageModel(ICheepRepository cheepRepository, IAuthorRepository authorRepository, IConfiguration config)
    {
        _cheepRepository = cheepRepository;
        _authorRepository = authorRepository;
        _config = config;
    }

    public async Task<IActionResult> OnGet()
    {
        // Handles the request when the user navigates to the About Me page.
        // Populates the variables used by the cshtml page to render the page.
        string? pagevalue = Request.Query["page"];

        OID = User.FindFirstValue(ClaimTypes.NameIdentifier);
        Author = User.Identity!.Name;
        Email = User.FindFirstValue("emails");
        if (pagevalue == null)
        {
            Cheeps = await _cheepRepository.GetCheepsFromAuthor(1, Author!);
        }
        else
        {
            Cheeps = await _cheepRepository.GetCheepsFromAuthor(Int32.Parse(pagevalue), Author!);
        }

        FollowedID = await _authorRepository.GetFollowedAuthors(Email);

        FollowersID = await _authorRepository.GetAuthorFollowers(Email);



        FollowedName = new List<string>();
        FollowersName = new List<string>();
        foreach (Guid id in FollowedID!)
        {

            string? user = await _authorRepository.GetAuthorNameByID(id);
            if (user != null)
            {
                FollowedName.Add(user);
            }
        }

        foreach (Guid id in FollowersID!)
        {

            string? user = await _authorRepository.GetAuthorNameByID(id);
            if (user != null)
            {
                FollowersName.Add(user);
            }
        }


        return Page();
    }

    public async Task<IActionResult> OnPostDelete(string UserOID, string UserEmail)
    {
        // The functionality to be run when the user clicks the "Forget Me!" button.
        try
        {
            var clientId = "e4f0f78c-3bcf-40d3-a75e-d6742a37053b";
            var tenantId = "ab2f43aa-cecc-43ed-a142-34012b9a7a3b";
            var clientSecret = _config["ConnectionStrings:DeleteSecret"];

            var scopes = new[] { "https://graph.microsoft.com/.default" };

            var options = new TokenCredentialOptions
            {
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
            };

            var clientSecretCredential = new ClientSecretCredential(
                tenantId, clientId, clientSecret, options);

            var graphClient = new GraphServiceClient(clientSecretCredential, scopes);

            // Delete User by ID
            await DeleteUserAsync(graphClient, UserOID);
            await _authorRepository.DeleteAuthor(UserEmail);

            Console.WriteLine($"User with username: {Author} deleted successfully.");
            string redirectUrl = "/MicrosoftIdentity/Account/SignOut";
            return Redirect(Url.Content(redirectUrl));
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error deleting user username: {Author}, {ex.Message}");
            string redirectUrl = "~/AboutMePage";
            return Redirect(Url.Content(redirectUrl));
        }
    }


    private async Task DeleteUserAsync(GraphServiceClient graphClient, string userId)
    {
        if (userId != null)
        {
            await graphClient.Users[userId].DeleteAsync();
        }
        else
        {
            throw new InvalidOperationException("User ID not found for the given email.");
        }
    }
}

src/Chirp.Web/Pages/AuthorAuthorize.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages;

public class AuthorAuthorizeModel : PageModel
{
    private readonly IAuthorRepository _repository;
    public AuthorAuthorizeModel(IAuthorRepository repository)
    {
        _repository = repository;
    }
    public async Task<IActionResult> OnGet() //use of Task https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-7.0
    {
        if (User.Identity != null)
        {
            if (User.Identity.IsAuthenticated)
            {
                AuthorDto? author = await _repository.GetAuthorDTOByEmail(User.FindFirstValue("emails")!);
                if (author == null)
                {
                    await _repository.CreateAuthor(User.Identity.Name!, User.FindFirstValue("emails")!);
                }
            }
            return Redirect(Url.Content("~/"));
        }
        else
        {
            return Page();
        }
    }
}

src/Chirp.Web/Pages/Components/CheepBox.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages.Components
{
    public class CheepBoxViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(CheepablePageModel model)
        {
            return View(model);
        }
    }
}

src/Chirp.Web/Pages/Discover.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;



namespace Chirp.Web.Pages;

public class DiscoverModel : PageModel
{
    // Holds the functionality and variables required to render the Discover page.

    public ICheepRepository _CheepRepository;
    public IAuthorRepository _AuthorRepository;
    public List<CheepDto>? Cheeps { get; set; }

    public List<Guid>? recomendedAuthors { get; set; }

    public List<CheepDto>? recomendedCheeps { get; set; }

    public List<Guid>? FollowedAuthors { get; set; }


    public int PageNumber { get; set; }

    public DiscoverModel(ICheepRepository repository, IAuthorRepository authorRepository)
    {
        _CheepRepository = repository;
        _AuthorRepository = authorRepository;
        recomendedCheeps = [];
        FollowedAuthors ??= new List<Guid>();
    }

    public async Task<IActionResult> OnGet() //use of Task https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-7.0
    {
        // Handles the request when the user navigates to the Discover page.
        recomendedAuthors = await _AuthorRepository.GetFollowersFollower(User.FindFirstValue("emails"));
        if (recomendedAuthors != null)
        {
            foreach (Guid authorId in recomendedAuthors)
            {
                CheepDto? cheepFromRecommendedAuthor = await _CheepRepository.GetFirstCheepFromAuthor(authorId);
                if (cheepFromRecommendedAuthor != null) recomendedCheeps!.Add(cheepFromRecommendedAuthor);
            }
        }


        //Use followauthors to show unfollow/follow button based on whether or not you follow authors
        FollowedAuthors = await _AuthorRepository.GetFollowedAuthors(User.FindFirstValue("emails"));

        return Page();
    }

    //https://www.learnrazorpages.com/razor-pages/handler-methods
    public async Task<IActionResult> OnPostFollow(string followName)
    {
        // Handles the request when the user clicks the Follow button.
        await _AuthorRepository.FollowAnAuthor(User.FindFirstValue("emails")!, followName);

        return Page();
    }

    public async Task<IActionResult> OnPostUnFollow(string followName)
    {
        // Handles the request when the user clicks the Unfollow button.
        await _AuthorRepository.UnFollowAnAuthor(User.FindFirstValue("emails")!, followName);

        return Page();
    }

}

src/Chirp.Web/Pages/Public.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;




namespace Chirp.Web.Pages;

public class PublicModel : Components.TimelinePageModel
{
    // Holds the functionality and variables required to render the Public page.
    // The functionality for the cheep box and follow/unfollow buttons come from the TimelinePageModel superclass.
    public ICheepRepository _cheepRepository;
    public IAuthorRepository _authorRepository;

    // Holds the list of cheeps to be displayed on the Public page.
    public List<CheepDto>? Cheeps { get; set; }

    // Holds the IDs of the authors that the user follows. This is useful for deciding whether to display the Follow or Unfollow button.
    public List<Guid>? FollowedAuthors { get; set; }

    // The page number of the current page of cheeps. Each page contains 32 cheeps.
    public int PageNumber { get; set; }

    // Asserts whether or not there is a next page of cheeps to be displayed.
    public bool HasNextPage;


    public PublicModel(ICheepRepository repository, IAuthorRepository authorRepository) : base(repository, authorRepository)
    {
        _cheepRepository = repository;
        _authorRepository = authorRepository;
    }

    public async Task<IActionResult> OnGet() //use of Task https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-7.0
    {
        // Handles the request when the user navigates to the Public page.
        string? pagestring = Request.Query["page"]; // A string containing the page number of the current page of cheeps.
        int pagevalue;
        if (pagestring == null) pagevalue = 1;
        else pagevalue = Int32.Parse(pagestring);
        PageNumber = pagevalue;
        // The page number is now decided. The cheeps can now be fetched from the database.

        // Fetch cheeps to be displyed.
        Cheeps = await _CheepRepository.GetCheeps(pagevalue);

        if (User.Identity!.IsAuthenticated)
        {
            // The followed authors are only initialised if the user is logged in. An unauthenticated user can not follow authors.
            FollowedAuthors ??= new List<Guid>();

            FollowedAuthors = await _AuthorRepository.GetFollowedAuthors(User.FindFirstValue("emails"));
        }
        HasNextPage = await _CheepRepository.HasNextPageOfPublicTimeline(pagevalue);
        return Page();
    }


}

src/Chirp.Web/Pages/UserTimeline.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;

namespace Chirp.Web.Pages;

public class UserTimelineModel : Components.TimelinePageModel
{
    // Holds the functionality and variables required to render the User Timeline page.
    // The functionality for the cheep box and follow/unfollow buttons come from the TimelinePageModel superclass.
    public ICheepRepository _cheepRepository;
    public IAuthorRepository _authorRepository;
    public List<CheepDto>? Cheeps { get; set; } // The list of cheeps to be dispalyed on the User Timeline page.
    public int PageNumber { get; set; } // The page number of the current page of cheeps. Each page contains 32 cheeps.

    public bool HasNextPage { get; set; } // Asserts whether or not there is a next page of cheeps to be displayed.

    // The IDs of the authors that the user follows. Followed users will also have their cheeps displayed on the User Timeline page.
    public List<Guid>? FollowedAuthors { get; set; }


    public UserTimelineModel(ICheepRepository cheepRepository, IAuthorRepository authorRepository) : base(cheepRepository, authorRepository)
    {
        _cheepRepository = cheepRepository;
        _authorRepository = authorRepository;
        FollowedAuthors = [];
    }

    public async Task<IActionResult> OnGet(string author)
    {
        string? pagevalue = Request.Query["page"]; // The page number provided as a string
        PageNumber = pagevalue == null ? 1 : Int32.Parse(pagevalue);
        // The page number is now decided. The cheeps can now be fetched from the database.

        // Fetch the followed authors
        FollowedAuthors = await _authorRepository.GetFollowedAuthors(User.FindFirstValue("emails"));
        // Checks if its the user timeline or another user timeline. User timelines of other users will not contain cheeps of the followed users.
        if (author == User.Identity!.Name)
        {
            Cheeps = await _cheepRepository.GetCheepsUserTimeline(PageNumber, author, FollowedAuthors!);
        }
        else
        {
            Cheeps = await _cheepRepository.GetCheepsFromAuthor(PageNumber, author);
        }

        // Assert if the next page button should be shown.
        HasNextPage = await _cheepRepository.HasNextPageOfPrivateTimeline(PageNumber, author, FollowedAuthors!);

        return Page();
    }

}

src/Chirp.Web/Pages/AboutMePage.cshtml
@page
@model Chirp.Web.Pages.AboutMePageModel

@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
}

<div>
   
    
    @if (User.Identity!.IsAuthenticated) {
        <h2> About you and your data </h2>
        <p> @Model.Author </p>
        <p> @Model.Email </p>

       

        <form method="post" id="deleteForm">
            <input type="hidden" name="UserOID" value="@Model.OID">
            <input type="hidden" name="UserEmail" value="@Model.Email">
            <input type="hidden" name="Handler" id="Handler" value=""> <!-- Add a hidden input for the handler -->
            <button type="button" onclick="confirmDelete()"
                style="background-color: red; color: white; border-color: darkred;">Forget Me!</button>
        </form>
        <br>

        <h2> Your Cheeps </h2>
        @if (Model.Cheeps != null && Model.Cheeps.Any())
        {
            <ul id=" messagelist" class="cheeps">
                @foreach (var cheep in Model.Cheeps)
                {
                    <li>
                        <p>
                            <strong>
                                <a href="/@cheep.Author">@cheep.Author</a>
                            </strong>
                            @cheep.Message
                            <small>&mdash; @cheep.Timestamp</small>
                        </p>
                    </li>
                }
            </ul>
        } else
        {
            <p> You haven't cheeped yet! </p>
        }
        <h2> People you follow </h2>
        @if (Model.FollowedName != null && Model.FollowedName.Any())
        {
            <ul id="followerlist" class="followers">
                @foreach (var follower in Model.FollowedName)
                {
                    <li>
                        <p>
                            <strong>
                                <a href="/@follower">@follower</a>
                            </strong>
                        </p>
                    </li>
                }
            </ul>
        }
        else
        {
            <p> You don't follow any people yet </p>
        }
        <h2> People who follow you </h2>
        @if (Model.FollowersName != null && Model.FollowersName.Any())
        {
            <ul id="followerlist" class="followers">
                @foreach (var follower in Model.FollowersName)
                {
                    <li>
                        <p>
                            <strong>
                                <a href="/@follower">@follower</a>
                            </strong>
                        </p>
                    </li>
                }
            </ul>
        }
        else
        {
            <p> No people follow you yet </p>
        }
    }
    else
    {
        <p> You are not logged in </p>
    }
</div>

<script>
    function confirmDelete() {
        var confirmResult = confirm("Are you sure you want to delete all your data on Chirp? \n \nThis action is permanent and cannot be undone");

        if (confirmResult) {
            // If the user clicks "OK" in the confirmation dialog, set the handler and submit the form
            document.getElementById('deleteForm').setAttribute('action', '?handler=Delete');
            document.getElementById('deleteForm').submit();
        }
        // If the user clicks "Cancel" in the confirmation dialog, do nothing
    }
</script>

src/Chirp.Web/Pages/AuthorAuthorize.cshtml
@* This page is used as a landing page after login. The content of this page is never shown. Its the model that is important
The model ensures that the logged in user is registered as an author in the database. 
*@

@page "/AuthorAuthorize"
@model Chirp.Web.Pages.AuthorAuthorizeModel

@if(User.Identity != null) {
    <div>
        <h1>@User.Identity.Name</h1>
    </div>
} else {
    <div>
        <h1>Authentication failed, please try again</h1>
    </div>
}

src/Chirp.Web/Pages/Discover.cshtml
@page
@model Chirp.Web.Pages.DiscoverModel

@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
}

<div>
    <h2> Discover </h2>
    @if(!User.Identity!.IsAuthenticated)
    {
        <p> <a href="/Identity/Account/Login"> Login </a> to see your feed. </p>
    }
    else
        @if (Model.recomendedCheeps != null && Model.recomendedCheeps.Any())
        {
            <ul id="messagelist" class="cheeps">
            @foreach (var cheep in Model.recomendedCheeps)
                {
                    <li>
                        <p>
                            <strong>
                                <a href="/@cheep.Author">@cheep.Author</a>
                            </strong>
                            @cheep.Message
                            <small>&mdash; @cheep.Timestamp</small>
                        </p>
                        
                        @if (User.Identity.IsAuthenticated && cheep.Author != User.Identity.Name)
                            {
                                @if (Model.FollowedAuthors!.Contains(cheep.AuthorId))
                                {
                                    <form method="post">
                                        <input type="hidden" name="followName" value="@cheep.Author">
                                        <button asp-page-handler="Unfollow">Unfollow</button>
                                    </form>
                                }
                                else
                                {
                                    <form method="post">
                                        <input type="hidden" name="followName" value="@cheep.Author">
                                        <button asp-page-handler="Follow">Follow</button>
                                    </form>
                                }
                            }

                    </li>
                }
            </ul>
        }
        else
        {
            <em> No posts found. Follow some people to get recomendations.</em>
        }
    }
</div>

src/Chirp.Web/Pages/Public.cshtml
@page "/"
@model Chirp.Web.Pages.PublicModel

@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
}

<div>
    <h2> Public Timeline </h2>

    @if (User.Identity!.IsAuthenticated)
    {
        <div class="cheepbox">
            <h3>What's on your mind @(User.Identity.Name)?</h3>
            <form method="post">
                <input style="float: left" type="text" asp-for="Text">
                <input type="submit" value="Share🚜">
                <p> @Model.validationMessage </p>
            </form>
        </div>
    }

    @if (Model.Cheeps != null && Model.Cheeps.Any())
    {
        <ul id="messagelist" class="cheeps">
            @foreach (var cheep in Model.Cheeps)
            {
                <li>
                    <p>
                        <strong>
                            <a href="/@cheep.Author">@cheep.Author</a>
                        </strong>
                        @cheep.Message
                        <small>&mdash; @cheep.Timestamp</small>
                    </p>

                    @if (User.Identity.IsAuthenticated && cheep.Author != User.Identity.Name)
                    {
                        @if (Model.FollowedAuthors!.Contains(cheep.AuthorId))
                        {
                            <form method="post">
                                <input type="hidden" name="followName" value="@cheep.Author">
                                <button asp-page-handler="Unfollow">Unfollow</button>
                            </form>
                        }
                        else
                        {
                            <form method="post">
                                <input type="hidden" name="followName" value="@cheep.Author">
                                <button asp-page-handler="Follow">Follow</button>
                            </form>
                        }
                    }

                </li>
            }
        </ul>
        <div class="navigation">

            @if (Model.PageNumber > 1)
            {
                <a href="/?page=@(Model.PageNumber - 1)"> Previous </a>
            }
            | <a href="/?page=@(Model.PageNumber)"> @(Model.PageNumber) </a> |
            @if (Model.HasNextPage)
            {
                <a href="/?page=@(Model.PageNumber + 1)"> Next </a>
            }

        </div>
    }
    else
    {
        <em>There are no cheeps so far.</em>
    }
</div>

src/Chirp.Web/Pages/UserTimeline.cshtml
@page "/{author}"
@model Chirp.Web.Pages.UserTimelineModel
@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
    var routeName = HttpContext.GetRouteValue("author");
}

<div>
    <h2> @routeName's Timeline </h2>

    @inject ICheepRepository CheepRepository
    @if (User.Identity != null && User.Identity.IsAuthenticated)
    {
        @await Component.InvokeAsync("CheepBox", Model)
    }

    @if (Model.Cheeps != null && Model.Cheeps.Any())
    {
                <ul id=" messagelist" class="cheeps">
            @foreach (var cheep in Model.Cheeps)
            {
                                <li>
                                    <p>
                                        <strong>
                                            <a href="/@cheep.Author">@cheep.Author</a>
                                        </strong>
                        @cheep.Message
                                        <small>&mdash; @cheep.Timestamp</small>
                                    </p>

                    @if (User.Identity != null && User.Identity.IsAuthenticated && cheep.Author != User.Identity.Name)
                    {
                        @if ((Model.FollowedAuthors ?? new List<Guid>()).Contains(cheep.AuthorId))
                        {
                                                            <form method="post">
                                                                <input type="hidden" name="followName" value="@cheep.Author">
                                                                <button asp-page-handler="Unfollow">Unfollow</button>
                                                            </form>
                        }
                        else
                        {
                                                            <form method="post">
                                                                <input type="hidden" name="followName" value="@cheep.Author">
                                                                <button asp-page-handler="Follow">Follow</button>
                                                            </form>
                        }
                    }
                                </li>
            }
                </ul>
                <div class="navigation">
            @if (Model.PageNumber > 1)
            {
                                <a href="/@routeName/?page=@(Model.PageNumber - 1)"> Previous </a>
            }
                    | <a href="/@routeName/?page=@(Model.PageNumber - 1)"> @Model.PageNumber</a> |
            @if (Model.HasNextPage)
            {
                                <a href="/@routeName/?page=@(Model.PageNumber + 1)"> Next </a>
            }

                </div>
    }

    else
    {
                <em>There are no cheeps so far.</em>
    }
</div>